<a href="https://colab.research.google.com/github/Bootcamp-DA-P3/Python-Analisis_Diego-Ramon/blob/main/LimpiezaR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En las siguiente celdas de código escribiremos cómo leer la base de datos (en nuestro caso, el muestreo pequeño de kiva loans) desde el drive. Además, al ser una carpeta compartida, hemos tenido que usar "force_remount=True" para asegurarnos que todos lo usuarios encuentran la ruta al archivo.
También revisaremos sus columnas, los tipos de datos que contiene (si es texto, numérico, moneda, etc)  y convertiremos columnas que debrían ser una fecha a datetime.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [3]:
#Inicializamos la librería "pandas"
import pandas as pd

# Cargamos el archivo CSV
df = pd.read_csv('/content/drive/MyDrive/Proyecto Limpieza Python/kiva_loans_42304_rows.csv')

# Mostramos las primeras filas del archivo para tener una visión inicial de cómo están organizados los datos
df.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,1175609,525.0,525.0,Personal Medical Expenses,Health,to buy medicines for her son’s treatment at th...,TJ,Tajikistan,Kanibadam,TJS,100.0,2016-10-27 04:54:27+00:00,2016-10-04 07:00:00+00:00,2016-11-05 02:14:03+00:00,14.0,18,#Health and Sanitation,female,monthly,2016-10-27
1,1056732,350.0,350.0,Butcher Shop,Food,to buy a refrigerator for his butcher shop,MX,Mexico,Ecatepec,MXN,294.0,2016-04-19 15:55:26+00:00,2016-03-31 07:00:00+00:00,2016-04-25 20:14:08+00:00,8.0,10,"#Elderly, #First Loan, #Health and Sanitation,...",male,monthly,2016-04-19
2,773348,225.0,225.0,Food,Food,to buy more raw ingredients for making food sn...,PH,Philippines,"Plaridel-Unidos, Plaridel, Misamis Occidental",PHP,126.0,2014-09-23 08:53:49+00:00,2014-09-19 07:00:00+00:00,2014-10-04 14:33:45+00:00,11.0,9,"volunteer_pick, volunteer_like, #Woman Owned Biz",female,irregular,2014-09-23
3,1076908,325.0,325.0,Farming,Agriculture,to purchase sacks of fertilizer,PH,Philippines,"Pagadian City, Zamboanga del Sur",PHP,126.0,2016-05-27 08:40:46+00:00,2016-05-10 07:00:00+00:00,2016-06-02 12:04:03+00:00,7.0,7,user_favorite,female,irregular,2016-05-27
4,680170,500.0,500.0,Poultry,Agriculture,To purchase more broiler chicks,ZW,Zimbabwe,Nyanga,USD,305.0,2014-03-06 10:29:22+00:00,2014-03-05 08:00:00+00:00,2014-04-02 01:31:55+00:00,8.0,11,"#Woman Owned Biz, #Parent, #Low-profit FP",female,irregular,2014-03-06

In [4]:
# Mostramos las columnas
df.columns

Index(['id', 'funded_amount', 'loan_amount', 'activity', 'sector', 'use',
       'country_code', 'country', 'region', 'currency', 'partner_id',
       'posted_time', 'disbursed_time', 'funded_time', 'term_in_months',
       'lender_count', 'tags', 'borrower_genders', 'repayment_interval',
       'date'],
      dtype='object')

In [5]:
# Mostramos los tipos de datos que son las columnas
df.dtypes

id                      int64
funded_amount         float64
loan_amount           float64
activity               object
sector                 object
use                    object
country_code           object
country                object
region                 object
currency               object
partner_id            float64
posted_time            object
disbursed_time         object
funded_time            object
term_in_months        float64
lender_count            int64
tags                   object
borrower_genders       object
repayment_interval     object
date                   object
dtype: object

In [7]:
# Convertimos las columnas que son una fecha (y son otro tipo distinto de dato) a tipo datetime
df['funded_time'] = pd.to_datetime(df['funded_time'], errors='coerce')
df['disbursed_time'] = pd.to_datetime(df['disbursed_time'], errors='coerce')
df['posted_time'] = pd.to_datetime(df['posted_time'], errors='coerce')

# Comprobamos que los cambios se han producido
df.dtypes

id                                  int64
funded_amount                     float64
loan_amount                       float64
activity                           object
sector                             object
use                                object
country_code                       object
country                            object
region                             object
currency                           object
partner_id                        float64
posted_time           datetime64[ns, UTC]
disbursed_time        datetime64[ns, UTC]
funded_time           datetime64[ns, UTC]
term_in_months                    float64
lender_count                        int64
tags                               object
borrower_genders                   object
repayment_interval                 object
date                               object
dtype: object

En las siguientes celdas procedemos a comprobar si hay duplicados exactos en el data set, es decir, si hay filas que son exactamente idénticas en todas sus columnas.

Si fuera el caso eliminaríamos una de las filas duplicadas ya que no aportaría nada al dataset. En este caso no hay duplicados.

In [11]:
# Comprobamos cuántos duplicados exactos existen en todo el DataFrame
duplicados_totales = df.duplicated().sum()
print(f"Número de filas duplicadas exactas en total: {duplicados_totales}")

Número de filas duplicadas exactas en total: 0

In [12]:
# 3 Comprobamos duplicados en la columna 'id' (se supone que es un identificador único)
duplicados_id = df.duplicated(subset=['id']).sum()
print(f"Número de préstamos con 'id' repetido: {duplicados_id}")

Número de préstamos con 'id' repetido: 0

In [13]:
# 5. Confirmar el tamaño final del DataFrame limpio
print(f"Nuevo total de filas tras eliminar duplicados: {df.shape[0]}")

Nuevo total de filas tras eliminar duplicados: 42308

En las siguiente celdas analizaremos si hay valores nulos o faltantes en las celdas del dataset. Primero veremos la cantidad de nulos que hay, y luego decidiremos que estrategia se debe llevar a cabo.
Puede haber casos que los valores nulos aporten información y no deban ser descartados

In [15]:
# Contamos la cantidad de valores nulos y su porcentaje en cada columna
nulos = df.isnull().sum()
porcentaje = (df.isnull().sum() / len(df)) * 100

#Hacemos una pequeña tabla con el número de nulos y su porcentaje para facilitar la visualización
resumen_nulos = pd.DataFrame({
    'nulos': nulos,
    'porcentaje (%)': porcentaje.round(2)
})
print(resumen_nulos)

                    nulos  porcentaje (%)
id                      0             0.0
funded_amount           0             0.0
loan_amount             0             0.0
activity                0             0.0
sector                  0             0.0
use                     0             0.0
country_code            0             0.0
country                 0             0.0
region                  0             0.0
currency                0             0.0
partner_id              0             0.0
posted_time             0             0.0
disbursed_time          0             0.0
funded_time             0             0.0
term_in_months          0             0.0
lender_count            0             0.0
tags                    0             0.0
borrower_genders        0             0.0
repayment_interval      0             0.0
date                    0             0.0

Vemos que no hay ningún dato nulo.
Puede que haya valores que representen un valor nulo pero el código no los identifique como tales. Para ello sustituiremos esos valores por NaN y repetiremos el proceso anterior.

In [16]:
# Sustituimos los valores (que son típicos de datasets) entre corchetes por un valor que el código detecta como nulo o faltante
df.replace(['', 'NA', 'N/A', 'null', 'None'], pd.NA, inplace=True)

# Repetimos el proceso anterior
nulos = df.isnull().sum()
porcentaje = (df.isnull().sum() / len(df)) * 100

resumen_nulos = pd.DataFrame({
    'nulos': nulos,
    'porcentaje (%)': porcentaje.round(2)
})
print(resumen_nulos)

                    nulos  porcentaje (%)
id                      0             0.0
funded_amount           0             0.0
loan_amount             0             0.0
activity                0             0.0
sector                  0             0.0
use                     0             0.0
country_code            0             0.0
country                 0             0.0
region                  0             0.0
currency                0             0.0
partner_id              0             0.0
posted_time             0             0.0
disbursed_time          0             0.0
funded_time             0             0.0
term_in_months          0             0.0
lender_count            0             0.0
tags                    0             0.0
borrower_genders        0             0.0
repayment_interval      0             0.0
date                    0             0.0

In [ ]:
df.to_csv('kiva_loans_clean.csv', index=False)